### ISSUE TITLE
Modify Info on Scenario Detail View

### ISSUE THREAD

**Issue by hdang32** [jeannie3/arc#1]
### Mock-up UI View (Left) as reference: 
https://drive.google.com/open?id=12jYTc2EvJ0-Rg3EdQjc97q0jxczcWMUZ

### Modifications to mock-up UI: 
 1) Remove the edit button (top right corner) since trainer is always in edit mode
 2) Remove AssignTo feature on the half right of the view since trainee takes the training anonymously.
 3) Remove 'Start' button since a trainer/creator shouldn't launch a training scenario within this Scenario Detail View
 4) 'Save' and 'Cancel' buttons always appear 

### Scenario Detail View is a view that contains basic information about the scenario:
 1) Title
 2) Description
 3) Created date

### Acceptance Criteria: 
 1) Scenario Detail View appears upon clicking a scenario
 2) Information (above) is editable within the view
 3) Trainer is able to save information 
 4) Trainer is able to discard all the changes in the detail view.

**Comment by jeannie3** [comment]
To save, we used cookies, but we should really set up an API and database for actual data persistence. Here is the corresponding story: (still creating the story)

**Comment by jeannie3** [comment]
PR: https://github.com/jeannie3/arc/pull/24
