### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by hdang32** [jeannie3/arc#28]
*** Check for updated schema in the comment ***
### Design:
Design table schemas for the SQL database (should contain *at least* the following tables)
1) Scenario table 
2) Scene Table
3) AnswerChoice table 
4) User table
5) Progress table 
6) Role table

### Acceptance Criteria: 
1) Relationship of Scenario : Role is 1 : Many
2) Relationship of Scene : AnswerChoice is 1 : Many 
3) There is no direct relationship between Scenario and AnswerChoice
4) Details of each table should contain all the fields listed in this picture: https://drive.google.com/open?id=1BKA2NSN_za5C0N7b9fmJZ0oW76bFh8ZX
5) Relationship of User : Progress is 1 : 1
6) Relationship of Role : Scene is 1 : Many

### Work: 
Draw out diagrams for Detail report of sprint 3
Only create sql statement if postgres doesn't work.

**Comment by hdang32** [comment]
We might not need "scenarioID" in Scene anymore if we let Scenario be referenced in Role and Role is referenced in Scene so Scene only knows which role a scene belongs to, and Role will know which scenario a role belongs to.

**Comment by sgundlapalli11** [comment]
What was the `type` attribute in `Scene` for? Was that how we differentiate between the `feedback ` and `cultural conflict` scenes?

**Comment by sgundlapalli11** [comment]
We may need to keep track of the nature of each `cultural conflict` (i.e. whether it is a positive or negative). I am currently trying to figure out how to determine displaying a positive or negative message in the `feedback` screen and believe we need to be keeping track of that information. 

Otherwise, we need to keep track of that information with the `feedback` potentially requiring us to separate `feedback` and `cultural conflicts` as objects. Also unsure of how we are going to link the last `cultural conflict` to the `feedback` screen.

**Comment by hdang32** [comment]
Aren't we going from an answer choice to a feedback screen?
I don't think we need to keep track of whether the cultural conflict is positive or negative because it's just the content. I feel like we're including unnecessary check type for these columns

**Comment by sgundlapalli11** [comment]
Okay makes sense. Hopefully Julio sends over the content soon so we see how he is formatting everything

**Comment by hdang32** [comment]
The type attribute for scene is to determine which one is Culture conflict (CC) or a feedback scene
Culture conflict scene contains (image, answer choice) 
feedback scene contains (explanation/ending message) and a button with different functionalities depending on the situation

**Comment by hdang32** [comment]
Created database tables with a few modification to the original schema
Entity Relationship Diagram: https://drive.google.com/open?id=1zI4G6FBsnIL_A5RCSYjSJ8zUw_qWCr8q
