### ISSUE TITLE
gamify training to provide incentives to replay same scenarios/roles

### ISSUE THREAD

**Issue by sgundlapalli11** [jeannie3/arc#35]

**Comment by hdang32** [comment]
@sgundlapalli11  What do you mean by gamify ?

**Comment by jeannie3** [comment]
@hdang32 It was basically to add points to each answer choice regardless of whether the answer choice is wrong or not, so the wrong answer choices will give less points than the correct answer choices, but the overall idea is that if we keep track of a high score, this will motivate the trainee to beat their own high score if they replay the same role.
