### ISSUE TITLE
choose conflict (behavior vs. scenario)

### ISSUE THREAD

**Issue by sgundlapalli11** [jeannie3/arc#37]
To be honest, this is the same conceptually as a conflict having two answer choices as this basically results in seeing another conflict. 

should be behavior vs situational (not scenario)

**Comment by hdang32** [comment]
Then why do you create a ticket for this?
It could be an acceptance criteria for another ticket which specifically handles displaying answer choices

**Comment by sgundlapalli11** [comment]
Conceptually its different, technically it could be the same. Didn't want to make a decision for the team so made a placeholder story for it until we discuss it in our next pointing/user stories meeting

**Comment by hdang32** [comment]
In implementation, we don't specify which one is behavioral or situational.
