### ISSUE TITLE
Choose Scenario 

### ISSUE THREAD

**Issue by jeannie3** [jeannie3/arc#49]
There are multiple scenarios and the trainee will choose one scenario to start training

![Scenario Select.PNG](https://images.zenhubusercontent.com/5928722651aa2c30577f950d/e961d9d3-e9fa-46ef-a76c-8a8ac2eb1e7c)

**Comment by hdang32** [comment]
Need to confirm with client on meeting 10/25 again 
So far, based on the previous meeting, client mentioned that trainee wouldn't get to choose which scenario to work on.

**Comment by jeannie3** [comment]
Since the client decided that scenarios are randomized, this story is no longer needed
