### ISSUE TITLE
Implement User Profile Settings

### ISSUE THREAD

**Issue by jeannie3** [jeannie3/arc#55]
Acceptance Criteria:

1) Implement the User Settings
2) Be able to view email of user
3) Be able to return to role selection screen
4) Be able to access from role selection screen
3) Change Password should take the user to User Settings Reset Password Screen (This will occur once a password reset screen has been implemented, for now it is non functional)

![image.png](https://images.zenhubusercontent.com/5928722651aa2c30577f950d/427e10bd-f6f9-491a-bdda-18fffc1719e3)

https://drive.google.com/open?id=1Zjc_T2DOzu6MrQA8vc3I4KnZDIlWoaNU

**Comment by hdang32** [comment]
@marcusj3 Can you upload your mockup here please

**Comment by marcusj3** [comment]
![User Settings.PNG](https://images.zenhubusercontent.com/5928722651aa2c30577f950d/4e4930f9-6394-4eb4-8e41-94c3de0fc7fa)
